aws_region = "us-east-1"
env = "dev"
rabbitmq_port = 5672
rabbitmqconsole_port = 15672
key_name = "Custom"
server_instance_type = "t3.micro"
ssh_port = 22
rabbit_exchanges = ["DataWarehouse", "Bootstrap", "Models"]
rabbit_users = ["joel", "amanda", "vivian", "jenny", "automation", "web"]
