variable "aws_region" {}
variable "env" {}
variable "http_port" {}
variable "key_name" {}
variable "server_instance_type" {}
variable "ssh_port" {}
variable "rabbitmq_port" {}
variable "rabbit_exchanges" {}
variable "rabbit_users" {}
